# Properties active for ALL profiles:
---
spring:
  cloud:
    config:
      uri: http://localhost:8001	# Expect the Spring Cloud Config server to be running on localhost, port 8001.  
server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

# Allow Eureka to recognize two apps of the same type on the same host as separate instances:
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}


# Depending on which profile is active, the application gives 
# itself a different name when registering with Eureka  spring.config.activate.on-profile
---
spring:
  config:
    activate:
      on-profile: subject
  application:
    name: subject
  
---
spring:
  config:
    activate:
      on-profile: verb
  application:
    name: verb

---
spring:
  config:
    activate:
      on-profile: article
  application:
    name: article

---
spring:
  config:
    activate:
      on-profile: adjective
  application:
    name: adjective

---
spring:
  config:
    activate:
      on-profile: noun
  application:
    name: noun
    
# This profile is used when running JUnit tests locally.  A spring.application.name must be provided.    
---      
spring:
  config:
    activate:
      on-profile: local-test
  application:
    name: local            
    
